name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
  BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-deps:
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    outputs:
      test-projects: ${{ steps.projects.outputs.test-projects }}
      build-projects: ${{ steps.projects.outputs.build-projects }}
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      # Rebase must happen before installing dependencies.
      - name: Rebase current branch
        run: node ./scripts/rebase-pr.js
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Get projects
        id: projects
        run: |
          echo "::set-output name=test-projects::$(npx nx print-affected --target=test | jq -cr '.tasks | map(.target.project)')"
          echo "::set-output name=build-projects::$(npx nx print-affected --target=build | jq -cr '.tasks | map(.target.project)')"

  lint:
    name: Lint
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      # Rebase must happen before installing dependencies.
      - name: Rebase current branch
        run: node ./scripts/rebase-pr.js
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Retrieve node_modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Check library dependencies
        run: npx skyux-dev check-lib-dependencies
      - name: Check library missing peers
        run: npx skyux-dev check-lib-missing-peers
      - name: Check library resources
        run: npx skyux-dev check-lib-resources
      - name: Check code formatting
        run: npx prettier --check .
      - name: Run lint
        run: npx nx affected:lint --quiet --silent --parallel --maxParallel=5 --skip-nx-cache

  build:
    name: Build
    needs: install-deps
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.install-deps.outputs.build-projects) }}
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      # Rebase must happen before installing dependencies.
      - name: Rebase current branch
        run: node ./scripts/rebase-pr.js
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Retrieve node_modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Build
        run: npx nx build ${{ matrix.project }} --skip-nx-cache

  build-dist:
    name: Build packages distribution
    needs: install-deps
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      # Rebase must happen before installing dependencies.
      - name: Rebase current branch
        run: node ./scripts/rebase-pr.js
      - name: Retrieve node_modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Build packages dist
        run: npx skyux-dev create-packages-dist

  coverage:
    name: Code coverage
    needs: install-deps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.install-deps.outputs.test-projects) }}
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      # Rebase must happen before installing dependencies.
      - name: Rebase current branch
        run: node ./scripts/rebase-pr.js
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Retrieve node_modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('package-lock.json') }}
      - name: Code coverage
        run: |
          npx nx test ${{ matrix.project }} --browsers=ChromeHeadless,WebkitHeadless --skip-nx-cache
          if [[ "$(nx print-affected --target=posttest | jq -r '.tasks | map(.target.project) | .[]' | grep -E '^${{ matrix.project }}$')" ]]
          then
            npx nx posttest ${{ matrix.project }} --browsers=ChromeHeadless,WebkitHeadless --skip-nx-cache
          fi
