name: Storybook

on:
  push:
    branches:
      - main
      - 6.x.x

env:
  PERCY_POSTINSTALL_BROWSER: true

jobs:
  install-deps:
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            !node_modules/.cache/nx
            /home/runner/.cache/Cypress
          key: cache-pr-preview-${{ hashFiles('package-lock.json') }}
      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          set -x
          node ./scripts/rebase-pr.js
          npm ci

  build-storybook:
    name: Build Storybook
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Retrieve dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            !node_modules/.cache/nx
            /home/runner/.cache/Cypress
          key: cache-pr-preview-${{ hashFiles('package-lock.json') }}
      - name: Retrieve nx cache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/nx
          key: cache-nx-storybook-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-nx-storybook-
            cache-nx-
      - name: Rebase current branch
        run: node ./scripts/rebase-pr.js
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Build Storybook
        run: npx nx run-many --target=build-storybook --configuration=ci --parallel=2 --exclude=storybook
      - name: Upload storybook artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook
          path: ./dist/storybook
          retention-days: 1
          if-no-files-found: error

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build-code-examples
      - build-playground
      - build-storybook
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits to identify current branches.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Retrieve dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            !node_modules/.cache/nx
            /home/runner/.cache/Cypress
          key: cache-pr-preview-${{ hashFiles('package-lock.json') }}
      - name: Retrieve nx cache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache/nx
          key: cache-nx-publish-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-nx-publish-
            cache-nx-
      - name: Download storybook artifact
        uses: actions/download-artifact@v3
        with:
          name: storybook
          path: ./dist/storybook
      - name: Build Storybook Composition
        run: |
          set -x
          jq -r '.projects | keys | join(",")' angular.json > ${{ runner.temp }}/affected_projects.txt
          for sb in ./dist/storybook/*
          do
            npx sb extract $sb
          done
          npx nx workspace-generator storybook-composition "$(<${{ runner.temp }}/affected_projects.txt)" --baseUrl https://blackbaud.github.io/skyux-storybook/storybooks/${{ github.ref_name }}/
          npx nx run storybook:build-storybook:ci
      - uses: actions/checkout@v3
        with:
          repository: 'blackbaud/skyux-storybook'
          ref: 'main'
          fetch-depth: 1
          path: skyux-storybook
          token: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
      - name: Remove old branch builds
        run: |
          set -x
          ls -d ./skyux-storybook/*/ | cut -f3 -d/ | sort > ${{ runner.temp }}/current_builds.txt
          git branch -r --format '%(refname:lstrip=3)' | tr -d ' ' | sort > ${{ runner.temp }}/expected_builds.txt
          if [[ -s "${{ runner.temp }}/current_builds.txt" && -s "${{ runner.temp }}/expected_builds.txt" ]]
          then
            # Get current builds that are not in expected.
            comm -23 ${{ runner.temp }}/current_builds.txt ${{ runner.temp }}/expected_builds.txt | tr -d ' ' > ${{ runner.temp }}/old_builds.txt
            if [[ -s "${{ runner.temp }}/old_builds.txt" ]]
            then
              git -C ./skyux-storybook rm -r -f --pathspec-from-file=${{ runner.temp }}/old_builds.txt
            else
              echo "All builds are current"
            fi
          else
            echo "Nothing to remove"
          fi
        env:
          GITHUB_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
      - name: Update branch build
        run: |
          set -x
          rm -rf ./skyux-storybook/${{ github.ref_name }} ./skyux-storybook/storybooks/${{ github.ref_name }}
          mkdir -p ./skyux-storybook/storybooks/${{ github.ref_name }}
          cp -R ./dist/storybook/storybook ./skyux-storybook/${{ github.ref_name }}
          for sb in ./dist/storybook/*
          do
            if [[ "${sb}" != "./dist/storybook/storybook" ]]
            then
              cp -R $sb ./skyux-storybook/storybooks/${{ github.ref_name }}/$(basename $sb)
            fi
          done
      - name: Commit build to GH Pages
        run: |
          set -x
          git config --global user.name "Blackbaud Sky Build User"
          git config --global user.email "sky-build-user@blackbaud.com"
          git -C ./skyux-storybook add --all
          git -C ./skyux-storybook status
          if [[ -n "$(git -C ./skyux-storybook status -s)" ]]
          then
            git -C ./skyux-storybook commit -m "$(printf 'skyux %s commit %s' ${{ github.ref_name }} ${GITHUB_SHA:0:8})"
            git -C ./skyux-storybook push
          else
            echo "No changes"
          fi

  e2e:
    name: End to end tests
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Retrieve dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            !node_modules/.cache/nx
            /home/runner/.cache/Cypress
          key: cache-pr-preview-${{ hashFiles('package-lock.json') }}
      - name: Percy e2e indicators
        run: npx percy exec -- nx run indicators-e2e:e2e:ci --skip-nx-cache --baseUrl https://blackbaud.github.io/skyux-pr-preview/${{ github.event.number }}/storybooks/indicators/
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN_INDICATORS_E2E}}
      - name: Percy e2e ag-grid-storybook
        run: npx percy exec -- nx run ag-grid-storybook-e2e:e2e:ci --skip-nx-cache --baseUrl https://blackbaud.github.io/skyux-pr-preview/${{ github.event.number }}/storybooks/ag-grid-storybook/
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN_AG_GRID_STORYBOOK_E2E}}
      - name: Percy e2e flyout-storybook
        run: npx percy exec -- nx run flyout-storybook-e2e:e2e:ci --skip-nx-cache --baseUrl https://blackbaud.github.io/skyux-pr-preview/${{ github.event.number }}/storybooks/flyout-storybook/
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN_FLYOUT_STORYBOOK_E2E}}
      - name: Percy e2e lists-storybook
        run: npx percy exec -- nx run lists-storybook-e2e:e2e:ci --skip-nx-cache --baseUrl https://blackbaud.github.io/skyux-pr-preview/${{ github.event.number }}/storybooks/lists-storybook/
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN_LISTS_STORYBOOK_E2E}}
      - name: Percy e2e popovers-storybook
        run: npx percy exec -- nx run popovers-storybook-e2e:e2e:ci --skip-nx-cache --baseUrl https://blackbaud.github.io/skyux-pr-preview/${{ github.event.number }}/storybooks/popovers-storybook/
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN_POPOVERS_STORYBOOK_E2E}}
      - name: Percy e2e tabs-storybook
        run: npx percy exec -- nx run tabs-storybook-e2e:e2e:ci --skip-nx-cache --baseUrl https://blackbaud.github.io/skyux-pr-preview/${{ github.event.number }}/storybooks/tabs-storybook/
        env:
          PERCY_TOKEN: ${{secrets.PERCY_TOKEN_TABS_STORYBOOK_E2E}}
