name: Visual regression tests

on:
  pull-request:
    branches:
      - main

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  install-deps:
    name: Install and cache dependencies
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.setup-node.outputs.node-version }}
      parameters: ${{ steps.affected-projects.outputs.parameters }}
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        id: setup-node
        with:
          node-version-file: '.nvmrc'
      # Rebase must happen before installing dependencies.
      - name: Rebase current branch
        run: node ./scripts/rebase-pr.js
      - name: Cache node modules
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: e2e-${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-modules-${{ hashFiles('package-lock.json') }}
      - name: npm install
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Start Nx Cloud CI run
        run: npx nx-cloud start-ci-run
      - name: Get affected projects
        id: affected-projects
        run: echo "parameters=$(npx skyux-dev e2e-workflow" >> $GITHUB_OUTPUT

  agents:
    name: Bootup Nx Cloud agent
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        agent: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: e2e-${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-modules-${{ hashFiles('package-lock.json') }}
      # Running ngcc after each agent is created to address the "ngcc is already running error".
      # Since we're running multiple builds in parallel, we need to pre-process our node_modules before starting the builds.
      - run: npx ngcc
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  e2e:
    name: Visual regression tests
    needs: install-deps
    runs-on: ubuntu-latest
    strategy:
      # If one build fails, do not cancel other builds.
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.install-deps.outputs.parameters).e2eMap }}
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      # Rebase must happen before installing dependencies.
      - name: Rebase current branch
        run: node ./scripts/rebase-pr.js
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - name: Retrieve node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ needs.install-deps.outputs.node-version }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Run NGCC
        run: npx ngcc
      - name: Percy ${{ matrix.project }}
        # Timing setting recommended by https://docs.percy.io/docs/cypress#missing-assets
        run: npx percy exec -t 350 -- nx e2e ${{ matrix.project }}-e2e --skip-nx-cache
        env:
          PERCY_TOKEN: ${{ secrets[matrix.token] }}

  stop-agents:
    name: Stop Nx Cloud agents
    runs-on: ubuntu-latest
    if: always()
    needs: [install-deps, e2e]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Retrieve node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: e2e-${{ runner.os }}-node-${{ steps.setup-node.outputs.node-version }}-modules-${{ hashFiles('package-lock.json') }}
      - name: Stop Nx Cloud agents
        run: npx nx-cloud stop-all-agents
